### ISSUE TITLE
Email when pending / approved?

### ISSUE THREAD

**Issue by LouGriffith** [strangerstudios/pmpro-approvals#10]
Would it be possible to send an email to the admin letting them know they have a pending user? 

Also it would great to notify the user via email when they have been approved.

**Comment by strangerstudios** [comment]
Hi, Lou. Note that this addon is still in active development and not stable yet. That said, those are good ideas and on our list of todos.

**Comment by andrewlimaza** [comment]
Hey Lou, I have added some of this functionality to PMPro Approvals. Busy testing it and getting approval from Jason regarding this.

So far I have done an admin email when user status is changed from pending to approved or pending to denied.

**Comment by LouGriffith** [comment]
Awesome! This will be a huge help to our project. Can't wait to test it out. Thank you!

**Comment by andrewlimaza** [comment]
This has been implemented @LouGriffith, we are still working through this with high priority as it's nearly ready for release (It should be somewhat working).
