### ISSUE TITLE
PMPRO version 2.1 fatal error

### ISSUE THREAD

**Issue by grifini** [strangerstudios/pmpro-approvals#106]
When PMPRO updated to version 2.1 the site has broken. I had PMPRO approvals plugin (partly working). I receive the following message after the crash.

Fatal error: Class 'PMProEmail' not found in .../public_html/wp-content/plugins/pmpro-approvals/classes/class.approvalemails.php on line 3

**Comment by andrewlimaza** [comment]
I managed to recreate this issue if Paid Memberships Pro is disabled. Please let me know if this error is occurring while Paid Memberships Pro 2.1 is installed and active.

**Comment by andrewlimaza** [comment]
I have created an issue for this - https://github.com/strangerstudios/pmpro-approvals/issues/107

**Comment by grifini** [comment]
Hi Andrew,
Yep that's exactly the case. Thank you for your reply.
