### ISSUE TITLE
New Member to be Approved before Payment

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/pmpro-approvals#108]
**Is your feature request related to a problem? Please describe.**
Members currently have to pay for the membership level before they are approved. This can put new members off in signing up as they would like to be approved first before paying, for example, the yearly membership. 

**Describe the solution you'd like**
An option for users to set the Approval add-on that members can check-out for the desired membership level without paying > status as 'pending'> admin approve the member > member notified with a link to check-out with the payment gateway > pay for the membership level & gain access.

**Describe alternatives you've considered**
Offer 'Approval first' OR 'Free' membership level & hide the other paying levels from the Levels page. Once the member is approved, they get sent a link to the 'hidden' levels to check out for the approved or correct membership level and check-out from there.

**Additional context**
I've had a couple of requests from users for this feature. They would like the process to be automated as the work-around or alternative can be time-consuming.

**Comment by andrewlimaza** [comment]
This is a bit tricky for initial payments as I don't think we're allowed to delay an initial payment.. What they can do is use the Subscription Delay Add On with a $0 initial payment. This won't be perfectly timed but will give admins a few days to approve the member and then bill the user (i.e. after 7 days etc).

Initial thoughts:

1. User signs up for a level with a 7 day trial.
2. Admins have a week (or longer depending on the trial) to approve these users.

** Users would still need to enter credit card details in this case, but will only be billed after the trial **

If you don't want to capture payment details on initial checkout, you would have to create a free membership level that requires approval and then prompt the user upon being approved to signup for a premium membership level.

It's difficult to not capture details for a paid membership level and then capture / bill the user once approved. This would require a manual process to prompt the user's to purchase etc.
