### ISSUE TITLE
Denying access not working w/ latest version

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-approvals#11]
Users are still able to access content to a page/post if they are awaiting approval.

**Comment by andrewlimaza** [comment]
For anyone that comes across this issue, we are busy rewriting this to support Multiple Members Per User

**Comment by arquera** [comment]
Hello! I had installed last version and i have this problem. Users with awaiting approval are able to access restricted content.

**Comment by andrewlimaza** [comment]
Hi @arquera 

Please open a support ticket on https://www.paidmembershipspro.com/support and someone from our team will be able to help figure this out with you.

We do not offer customer support through Github. Thank you for understanding.
