### ISSUE TITLE
Auto approve old members when they renew their membership

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-approvals#117]
When members renew their subscription, they need to be approved once again before regaining access to the site content.

We could add a way to auto approve old members who have renewed their subscription without having them go through the process of approval again.

An alternative will be to write a custom code to help achieve this. But this may also take some time, hence having it be a feature is a much better option.

**Comment by tictag** [comment]
Some PMPro customers (like me) would want memberships to be re-approved on renewal e.g. we have a 'concessionary' membership for those people on state benefits, such members would need to provide evidence that they are still on state benefits on renewal.

Optionally providing this feature would, however, be useful. I can see where 'auto approval on renewal' on a per membership level and per user basis would come in handy.

**Comment by MaryOJob** [comment]
This feature can be added as a filter that custom code can disable - just in case a site owner wants to always force re-approval.

**Comment by andrewlimaza** [comment]
Duplicate ticket here - https://github.com/strangerstudios/pmpro-approvals/issues/86

**Comment by andrewlimaza** [comment]
I think a gist (for now) would make more sense.
