### ISSUE TITLE
Approval Notification Still Shows when No Users are Pending

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/pmpro-approvals#124]
**Describe the bug**

Approvals in admin still show as needing approval even when no approvals are pending.

<img width="428" alt="Screen Shot 2020-06-26 at 6 28 57 AM" src="https://user-images.githubusercontent.com/636521/85852505-5945ec00-b776-11ea-9fa5-3a1d889fd217.png">

**To Reproduce**
1. Enable the Approvals Add On for Level X
2. User checkouts for Level X - Status is pending
3. User re-checks out for level Y, which doesn't require admin approval
4. PMPro still displays an approval needed, even though there are no pending approvals.

**Expected behavior**

Approvals should be cleared if a user re-checks out for a level that is not in approval status.

**Workaround**

Delete the user meta key starting with `pmpro_approval` for the user in question in user meta table.
Delete transient `pmpro_approvals_approval_count` in options table.

**Comment by gausam** [comment]
Tested and it appears this will be fixed by https://github.com/strangerstudios/pmpro-approvals/pull/127, like you said @andrewlimaza.

**Comment by ghittisak** [comment]
me too , cloud you please guide for correct ?

**Comment by andrewlimaza** [comment]
@ghittisak, here's the pre-release -> https://github.com/strangerstudios/pmpro-approvals/pull/127

**Comment by andrewlimaza** [comment]
This has been fixed and merged into 'dev' branch now.
