### ISSUE TITLE
Pending users can't cancel membership

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-approvals#126]
**Describe the bug**
if a user is in Pending status and the user decides to cancel their account BEFORE it has been approved, and he/she clicks on the Cancel link, nothing happens. It just goes straight back to the Account Details page.

**To Reproduce**
1. Subscribe to a level that requires approval
2. While still pending, go to the membership account page and try to cancel
3. It just reloads the Membership Account page without canceling the account

**Expected behavior**
1. There should at least be a message stating that the account is still awaiting admin approval and cannot be canceled at this time.
or
2. The user should be allowed to cancel their pending account.

**Comment by andrewlimaza** [comment]
Resolved and will be pushed out in next release.
