### ISSUE TITLE
BUG: Approvals AddOn – Member (Re)Approved If Screen Refreshed

### ISSUE THREAD

**Issue by tictag** [strangerstudios/pmpro-approvals#138]
**MODS ONLY** Relates to support ticket: https://www.paidmembershipspro.com/forums/topic/bug-approvals-addon-member-reapproved-if-screen-refreshed

**Describe the bug**
When a member requires approval I can visit the Approvals page and Approve. This works fine.

If for some reason I then want to refresh the approvals page, clicking browser ‘refresh’ re-approves that member. Refresh 5 times, the member is re-approved 5 times. 5 new emails go out to the member. 5 new emails go out to admin.

A member should only be approved once, irrespective of whether or not the Approvals screen is refreshed.

**To Reproduce**
Please refer to this video screencast showing step-by-step how to re-create this issue: https://1drv.ms/u/s!AiwD9-8HyNC59wBivKWAqMP-iMd5?e=X5kh1a

**Screenshots**
Provided above.

**Expected behavior**
A member should only be approved once, irrespective of whether or not the Approvals screen is refreshed.

**WordPress Environment**
<details>
```
PHP v7.3.20
WordPress v5.5.1
PMPro v2.5.1
Approvals Addon v1.3.4
```
</details>

**Comment by andrewlimaza** [comment]
This has been fixed in latest push to dev, this will be included in the next release.
