### ISSUE TITLE
BUG: Approvals Addon – PHP Notice On Viewing Approval Page

### ISSUE THREAD

**Issue by tictag** [strangerstudios/pmpro-approvals#139]
**MODS ONLY** Relates to support ticket: https://www.paidmembershipspro.com/forums/topic/bug-approvals-addon-php-notice-on-viewing-approval-page

**Describe the bug**
Running some rudimentary tests post update to PMPro v2.5.1. Standard checkout of membership level requiring approval completes successfully. On viewing Approval page, following PHP notice is recorded:

[17-Nov-2020 16:26:50 UTC] PHP Notice: Trying to get property ‘label’ of non-object in /home/customer/www/dev.ksa-uk.net/public_html/wp/wp-content/plugins/pmpro-approvals/adminpages/userinfo.php on line 104

Note: Everything seems to work OK, so this is a low priority ‘when time permits’ bug.

**To Reproduce**
Video screencast step-by-step: https://1drv.ms/v/s!AiwD9-8HyNC59n5VxgaXnh4HkCe9?e=2k3eHn

**Screenshots**
Provided above.

**Expected behavior**
Please help me to view the approvals page without errors being logged in the debug log.

**WordPress Environment**
<details>
PHP v7.3.20
WordPress v5.5.1
PMPro v2.5.1
</details>

**Comment by andrewlimaza** [comment]
This has been fixed and will go out in the next release, you may pull from 'dev' branch to pre-patch your site if needed.
