### ISSUE TITLE
Conflicts with Multiple Memberships Per User

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-approvals#143]
There are a couple of edge-cases that don't make sense when using MMPU and Approvals:

1. If the user signs up for multiple levels at a single checkout or before approved. Approving the member will approve access to all levels immediately.
2. If the user signs up for a level, gets approved and then purchases another level at a later stage. Admins cannot approve the user as they are showing as approved inside the 'pending' level.

**Comment by michaelbeil** [comment]
A member reported this in ticket 373710 (**moderators only**).

**Comment by andrewlimaza** [comment]
Related -> https://github.com/strangerstudios/pmpro-approvals/issues/71

**Comment by michaelbeil** [comment]
This came up in ticket 436021 (**moderators only**):
>trying to create 2 membership levels for a local organization. general public can view the site(no membership needed), an employee with restricted content access(membership level needed), tribal member with restricted content access apart from public and employee(membership level needed). There is a very probable scenario where you can be an employee AND a tribal member. So you’d need access to both the employee restricted content and Tribal Member Restricted Content. But approval is required for the Tribal Member membership level. The employee membership level is email domain restricted, but needs to be restricted only if selecting employee membership level. I have seen that there are issues with MMPU but trying to see if we can facilitate what I’m looking to do with out having to have the approvals and MMPU work together.
