### ISSUE TITLE
Bug membership shortcode, when level is set to 0, does not work when Approvals Add On is Active

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-approvals#149]
**Describe the bug**
When a page is using the membership shortcode `[membership level="0"]`  and Approvals Add On is active, the content does not hide the content from logged-in members as it should.   

**To Reproduce**
1.  Activate PMPro.
2.  Create a page using the shortcode "[membership level="0"]Members Should Not See This[/membership]"
3. log in as a user. 
4. Go to the new page.
4. The message will not appear.
4. Activate Approval Add On
5. log in as a user. 
5. Go to the new page.
6. Message is not hidden from logged-in member.

**Screenshots**
![should-be-hidden](https://user-images.githubusercontent.com/8083630/131674106-435c1db5-ea94-4104-96ec-e2aed9ce561d.png)

**Expected behavior**
[membership level="0"]  Should hide content from members.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Multiple environments. Tested with WordPress 5.8, PMPro 2.6.1.1, and Approval Add On 1.4
```
</details>

**Comment by andrewlimaza** [comment]
I am unable to replicate this issue on my end.

These are the steps I've followed:

1. Tested shortcode `[membership level="0"]This is for non-members[/membership]` (As well as the default `[membership]` shortcode).
2. View the page this shortcode is on, while as a pending member. (Both don't show, we could probably show level="0" to pending members but it's not critical IMO).
3. Viewed in incognito while logged out "This is for non-members" showed.

The membership level="0" is for non-members. This may include logged-in non-members as well or visitors. Can you tell me more about this test user you are testing with, are they approved/denied or pending approval?

**Comment by andrewlimaza** [comment]
I have managed to replicate this for approved members, I'm assuming that it's affecting grandfathered (pre-existing/approved) members. Working on a fix for this now.

**Comment by andrewlimaza** [comment]
Fixed this here -> https://github.com/strangerstudios/pmpro-approvals/commit/c7f46da54774a9ed2d36e3565300f76568b6e842

It seems no level shortcode attribute and negative shortcode attributes work for approved members. Still testing this, fix to be included in upcoming release.
