### ISSUE TITLE
BUG: Conflict w/ Approvals and Email Confirmation Add On

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-approvals#155]
**Describe the bug**
When a site has Approvals and Email Confirmation Enabled, at checkout, the user will show as PENDING on checkout page, but then say APPROVED on Members Account Page. The user will have access to restricted Content.

They are still on the "needs approval list" on the back end.

After new members confirm their Email address with the link they are emailed, they will appear PENDING on the Members Account Page.

**To Reproduce**
1. Install and Activate Approval Add On and Email Confirmation Add On
2. Set up Level to require both of the above.
3. Check out for this level
4. See Pending on Confirmation Page, the Approved on Members Account Page
5. Levels page says YOUR LEVEL, rather then Approval Pending
6. Confirm email with linked emailed to the user.
7. See status changed to Pending.

**Screenshots**
![ConfirmationPage](https://user-images.githubusercontent.com/8083630/156788072-30fe5595-f942-4e98-bb88-05f1e08a20e2.png)
![AccountPage](https://user-images.githubusercontent.com/8083630/156788093-ec256000-95d9-4d3c-9418-7463d625b071.png)

**Expected behavior**
The user should stay PENDING until Email Confirmation and Approval are given.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WP 5.9.1
PMPro 2.7.5
```
</details>

**Comment by andrewlimaza** [comment]
I've began to test this, I don't see this anymore. I'm assuming one of the merges (most likely merging MMPU functionality into PMPro Approvals has resolved this). I am closing this issue as it is resolved.
