### ISSUE TITLE
User Fields not showing on the "View" page 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-approvals#165]
**Describe the bug**
Approvals has code to pull in the (former) Register Helper fields to the "View" approval screen here: https://github.com/strangerstudios/pmpro-approvals/blob/dev/adminpages/userinfo.php#L102. This isn't working with the new User Fields features in core PMPro.

We need to add this in since some people processing approvals (the approver role) won't also have edit user access to see fields.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dwanjuki** [comment]
A user encountered this bug.
Mods: #518168

**Comment by dwanjuki** [comment]
Resolved by #174
