### ISSUE TITLE
Warning on PHP 8.2.3

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-approvals#169]
**Describe the bug**
A customer ran into an error on PHP 8.2.3.

**To Reproduce**
Steps to reproduce the behavior for customer:
1. Set PHP version to PHP 8.2.3
2. Activate Paid Memberships Pro, and Approvals Add On. See this error:

```
Warning: Attempt to read property “name” on bool in /home/customer/www/xxyy/public_html/wp-content/plugins/pmpro-approvals/pmpro-approvals.php on line 1417
```

**Expected behavior**
There should not be an error.

This came up in ticket 482012 on PHP 8.2.3, but I couldn't replicate on PHP 8.1.9

**WordPress Environment**
<details> 
Paid Memberships Pro 2.10.2, and Approvals Add On 1.5, WordPress 6.1.1, PHP 8.2.3
</details>

**Comment by andrewlimaza** [comment]
Looks like this has been resolved, I do not get this error when activating Approvals. I will close this issue and reopen it if we notice this come up in future tickets.
