### ISSUE TITLE
User Fields are not showing on the "View" page

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-approvals#180]
**Describe the bug**
Clicking on "View" to approve or deny a member should show custom user fields on the view page. This is not being displayed for the admin.

**To Reproduce**
1. Activate Approvals Add-On and set up a level to require approval
2. Create a custom user field
3. Run a test checkout in another browser, and as a logged in admin in your main browser, go to Approvals, click on "View" on any user requiring approval
4. The custom field is not displayed

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.
<img width="534" alt="Screenshot 2023-11-17 at 11 26 48" src="https://github.com/strangerstudios/pmpro-approvals/assets/25005583/2133759b-55ee-4330-8de5-f3bbeaa83c55">

**Expected behavior**
Custom user fields should be displayed on the "view" page for the Approvals Add-On

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress Version 6.4.1
PMPro Version 2.12.4
PMPro Approvals Add-On Version 1.5
Memberlite 5.0.0
PHP Version 8.0.30
```
</details>

**Comment by dwanjuki** [comment]
#174 resolves this issue
