### ISSUE TITLE
Emails do not str_replace !!variables!!

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-approvals#28]
If you use the email templates add-on or simply edit the email template directly. Variables such as !!name!! are not replaced with the correct value.

**Comment by andrewlimaza** [comment]
This is only for admin emails that are sent out.

**Comment by andrewlimaza** [comment]
Update on this, apparently variables send through admin details and not the user that is approved. Needs some testing.

**Comment by ideadude** [comment]
We need to check the priorities/etc for when we swap in data and the pmpro emails addon does.

**Comment by andrewlimaza** [comment]
There is a pull request to handle this AFAIK. Will be testing and tidying this up a bit.

**Comment by greathmaster** [comment]
Possible related issue mentioned here in private support ticket:

https://www.paidmembershipspro.com/forums/topic/pmpro-approvals-plugin/

**Comment by andrewlimaza** [comment]
I believe this is now fixed.
