### ISSUE TITLE
No automation on denials

### ISSUE THREAD

**Issue by cdgdigital** [strangerstudios/pmpro-approvals#31]
When a new "prospect member" has its MEMBERSHIP DENIED, what happens is only an email sent to that member and to admin; there is no refund request sent to PayPal, there is no change on invoice status, there is no change on membership status, there is no indicators on reports, and the member continues to show up on the Directory.

The expected behavior after a MEMBERSHIP DENIAL should be:
- prospect member receives an email;
- if prospect has already paid, a refund request is sent to PayPal or other gateway;
- the sales report is updated with the refund;
- the membership requested status is cancelled.

In addition, a "denial reason" field on the approval screen should also be very useful for adding on the email sent to the denied prospect member.

**Comment by andrewlimaza** [comment]
Thank you for creating this issue. I definitely think this is something our team needs to think about. 
There are quite a few use-cases surrounding this plugin (not all user's will want to terminate the user's membership in some cases and others won't want to automatically refund the user) and I do believe it will adapt as those cases are received, so thank you for your input it does help us decide where to go next with the plugin.

I definitely agree with a 'Reason' when denying the users and this is on our development schedule and possibly adding in an option to the plugin to automatically refund/cancel the user's membership (We are working on some guides with the PMPro Approvals add on).

I hope this somewhat helps :) - If you need these features urgently you may reach out to one of our recommended developers on https://www.paidmembershipspro.com/developers

**Comment by jezkerwin** [comment]
Has there been any more thought to this issue? I also agree in the process for denying a member. The manual process of cancelling a membership and issuing a refund seems core that this plugin should do when denying a member, otherwise what's the point of the plugin, it's only got half functionality

**Comment by MaryOJob** [comment]
Similar: ##420122 (Moderators Only)

Request to have a user deleted when their membership is denied.

**Comment by flexerd** [comment]
To add  my voice to a need to at least give the option especially important in free levels, as those get many spammers signing up. In addition to this being a security risk it makes it difficult to expand the plugin = We created three test users, applied not approved, approved and denied and it seems that all three have identical user profiles at runtime.

**Comment by andrewlimaza** [comment]
This isn't something we plan on supporting, as PMPro core doesn't do this at all. (Right now you need a gist to delete user's on level cancel in PMPro core and this can be catastrophic for some not knowing this will happen, as it may cancel subscriptions etc).

Here is a gist you may use to delete user's on denying the user -> https://gist.github.com/andrewlimaza/c8d6a2636112625e41b19bdefc03205a
