### ISSUE TITLE
Access to BuddyPress pages

### ISSUE THREAD

**Issue by jasperhampton** [strangerstudios/pmpro-approvals#43]
Access to BuddyPress pages is being granted to non approved members.

**Comment by kimcoleman** [comment]
We have an update about to release that makes the Approvals Add On compatible with the BuddyPress Integration for Paid Memberships Pro. Are you using the BuddyPress Integration for Paid Memberships Pro to restrict access to your BuddyPress site? (https://www.paidmembershipspro.com/add-ons/buddypress-integration/)

**Comment by andrewlimaza** [comment]
@jasperhampton are you still having issues with this?

**Comment by andrewlimaza** [comment]
I've submitted a PR that should potentially fix this - https://github.com/strangerstudios/pmpro-approvals/pull/58

**Comment by andrewlimaza** [comment]
You may be able to use this code recipe if you are still experiencing this issue - https://gist.github.com/andrewlimaza/037019112e4d7a55ae4fb8c6cbe9a33d

**Comment by andrewlimaza** [comment]
I am going to close this issue as there has been no update to this issue. If you are still experiencing this issue please feel free to open a new issue on Github or reach out to our support on www.paidmembershipspro.com
