### ISSUE TITLE
Integrate with Member Directory Add On

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-approvals#48]
If a user is pending / denied they still show up on the member directory page. We should integrate with this and adjust it accordingly to only show approved members.

**Comment by andrewlimaza** [comment]
Reference: https://github.com/strangerstudios/pmpro-member-directory/blob/master/templates/directory.php#L112

**Comment by eighty20results** [comment]
Easily handled in `pmpro_approvals_after_approve_member`, `pmpro_approvals_after_deny_member` and `pmpro_approvals_after_reset_member` action hooks with the following code recipe:

`
function changeDirectoryVisibility( $user_id, $membership_level_id ) {
		
		$show_if_approved        = true;
		$level_requires_approval = \PMPro_Approvals::requiresApproval( $membership_level_id );
		$user_is_approved        = \PMPro_Approvals::isApproved( $user_id, $membership_level_id );
		
		if ( false === $level_requires_approval ) {
			update_user_meta( $user_id, 'pmpromd_hide_directory', false );
		}
		
		// Set to 'do not display in directory' if the user isn't approved.
		if ( true === $level_requires_approval && true === $show_if_approved && false === $user_is_approved ) {
			update_user_meta( $user_id, 'pmpromd_hide_directory', true );
		}
		
		if ( true === $level_requires_approval && true === $show_if_approved && true === $user_is_approved ) {
			update_user_meta( $user_id, 'pmpromd_hide_directory', false );
		}
	}

        add_action( 'pmpro_approvals_after_approve_member', 'changeDirectoryVisibility', 10, 2 );
        add_action( 'pmpro_approvals_after_deny_member', 'changeDirectoryVisibility', 10, 2 );
        add_action( 'pmpro_approvals_after_reset_member', 'changeDirectoryVisibility', 10, 2 );
`

**Comment by andrewlimaza** [comment]
PR to fix this: https://github.com/strangerstudios/pmpro-approvals/pull/83
