### ISSUE TITLE
Enhancement: Hide "Status" on Account page for levels which do not require approval.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-approvals#52]
The "Status" bullet point is added to the Account page for all levels, even if they don't require approval. This may be confusing to some users.

**Support Ticket (Moderators Only)**:
https://www.paidmembershipspro.com/forums/topic/status-field-input-on-profile-page/#post-176923

**Comment by andrewlimaza** [comment]
Fixed: https://github.com/strangerstudios/pmpro-approvals/pull/80
