### ISSUE TITLE
Bug:(Pending) link isn't rendered correctly in 2.0 Recent Members widget

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-approvals#54]
If a member is in "pending" status, the "(Pending)" link appended to their membership level name isn't rendering correctly in the new Recent Members widget in the Memberships Dashboard of PMPro v2.0+

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/new-dashboard-does-not-show-approvals-area-anymore/

**Comment by ioamnesia** [comment]
I've submitted pull request #55 to fix this...
