### ISSUE TITLE
Wrong username in member emails

### ISSUE THREAD

**Issue by talkytoaster** [strangerstudios/pmpro-approvals#63]
I've noticed that the emails sent to members when approved has the site-admin name rather than the member name in them, think this is a bug. Seen the reverse happening when admin is receiving emails about pending accounts; these have the member name instead of the admin name, as in Dear Harold Blue, rather than Dear Site Admin...

I'm currently testing your software out and I see m to be finding far too many issues.

**Comment by andrewlimaza** [comment]
Hi @talkytoaster 

An update for this is coming out this week (if all is well) that will address this issue and highly improve the email system.

For a sneak peek, you can use the dev branch for this repo.

I'm sorry for the inconvenience cused by this.

**Comment by ideadude** [comment]
I thought this was the commit that fixed this, but maybe needs more testing: https://github.com/strangerstudios/pmpro-approvals/commit/46111aff040580c4aa1ed87d3f7c7b0e1875f66f

**Comment by femiyb** [comment]
It seems this hasn't been fixed as this user said updating didn't fix the issue.
https://www.paidmembershipspro.com/forums/topic/admin-details-being-sent-instead-of-user-details-and-shortcodes-in-subject-lines/

**Comment by talkytoaster** [comment]
I found a fix by changing the Email Header template to not include !!name!!, not ideal but better than it was...

**Comment by andrewlimaza** [comment]
Closing this as I believe it's been resolved in the latest updates. This will be released in the near future.
