### ISSUE TITLE
Plugin installed but not working

### ISSUE THREAD

**Issue by elissonkario** [strangerstudios/pmpro-approvals#7]
this plugin is a light at the end of the tunnel. Thank you for sharing it. I installed following the guidance. The plugin is active and its functions are listed in the wordpress panel. However it is not working for me. After selecting the "Requires Approval: "and I subscribe to this plan, the user has immediate access to the content ... can you help me?

**Comment by andrewlimaza** [comment]
Hey @elissonkario 

We are still currently developing this add-on and isn't fully ready yet. It should be available in the near future.

I apologize for the inconvenience caused.

**Comment by andrewlimaza** [comment]
Hi @elissonkario 

We have made major improvements to PMPro Approvals and it's nearly ready to be tested and released. It should be working (with a possibility of bugs).
