### ISSUE TITLE
Approvals Process For Membership Add On: Deprecated 'Pending' feature?

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-approvals#95]
Prior to v1.3 of the Approvals Process For Membership Add On, the members list displayed ‘Pending’ beneath the membership level. Clicking the ‘Pending’ link took you to the approvals page.

Since v1.3 this ‘Pending’ status no longer displays – see attached screenshots.

Was this feature deprecated? I saw no notice of this in the release notes for the update.

![image](https://user-images.githubusercontent.com/22073464/62050829-5236f680-b212-11e9-99fa-231a7dcc74a9.png)

**Comment by andrewlimaza** [comment]
This has been merged in :)
